# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: jasmine
description: Broadcast prerecordings app 🛋️
docs: true
docsurl: https://radio-aktywne.github.io/jasmine
envprefix: JASMINE
imagename: apps/jasmine
keyprefix: jasmine
port: 10620
registry: true
releases: true
reponame: jasmine
repourl: https://github.com/radio-aktywne/jasmine
