# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.0
_src_path: gh:radio-aktywne/template-app-next
accountname: radio-aktywne
appname: weblounge
description: Broadcast prerecordings app 🛋️
docs: true
docsurl: https://radio-aktywne.github.io/weblounge
envprefix: WEBLOUNGE
imagename: apps/weblounge
keyprefix: weblounge
port: 39000
registry: true
releases: true
reponame: weblounge
repourl: https://github.com/radio-aktywne/weblounge
