services:
  jasmine:
    build:
      context: ./
      network: host
    environment:
      - "JASMINE__APIS__BEAVER__HOST=${JASMINE__APIS__BEAVER__HOST:-localhost}"
      - "JASMINE__APIS__BEAVER__PATH=${JASMINE__APIS__BEAVER__PATH:-}"
      - "JASMINE__APIS__BEAVER__PORT=${JASMINE__APIS__BEAVER__PORT:-10500}"
      - "JASMINE__APIS__BEAVER__SCHEME=${JASMINE__APIS__BEAVER__SCHEME:-http}"
      - "JASMINE__APIS__ICANHAZDADJOKE__HOST=${JASMINE__APIS__ICANHAZDADJOKE__HOST:-icanhazdadjoke.com}"
      - "JASMINE__APIS__ICANHAZDADJOKE__PATH=${JASMINE__APIS__ICANHAZDADJOKE__PATH:-}"
      - "JASMINE__APIS__ICANHAZDADJOKE__PORT=${JASMINE__APIS__ICANHAZDADJOKE__PORT:-}"
      - "JASMINE__APIS__ICANHAZDADJOKE__SCHEME=${JASMINE__APIS__ICANHAZDADJOKE__SCHEME:-https}"
      - "JASMINE__APIS__NUMBAT__HOST=${JASMINE__APIS__NUMBAT__HOST:-localhost}"
      - "JASMINE__APIS__NUMBAT__PATH=${JASMINE__APIS__NUMBAT__PATH:-}"
      - "JASMINE__APIS__NUMBAT__PORT=${JASMINE__APIS__NUMBAT__PORT:-10600}"
      - "JASMINE__APIS__NUMBAT__SCHEME=${JASMINE__APIS__NUMBAT__SCHEME:-http}"
      - "JASMINE__DEBUG=${JASMINE__DEBUG:-true}"
      - "JASMINE__SERVER__HOST=${JASMINE__SERVER__HOST:-0.0.0.0}"
      - "JASMINE__SERVER__PORT=${JASMINE__SERVER__PORT:-10620}"
    network_mode: host
