// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import {
  PingHeadpingRequestSchema,
  PingHeadpingResponseSchema,
  PingPingRequestSchema,
  PingPingResponseSchema,
  PrerecordingsEventListRequestSchema,
  PrerecordingsEventListResponseSchema,
  PrerecordingsEventStartDeleteRequestSchema,
  PrerecordingsEventStartDeleteResponseSchema,
  PrerecordingsEventStartDownloadRequestSchema,
  PrerecordingsEventStartDownloadResponseSchema,
  PrerecordingsEventStartHeaddownloadRequestSchema,
  PrerecordingsEventStartUploadRequestSchema,
  PrerecordingsEventStartUploadResponseSchema,
  SseSubscribeRequestSchema,
  SseSubscribeResponseSchema,
  TestTestRequestSchema,
  TestTestResponseSchema,
} from "./schemas";
import type {
  PingHeadpingRequest,
  PingHeadpingResponses,
  PingPingRequest,
  PingPingResponses,
  PrerecordingsEventListErrors,
  PrerecordingsEventListRequest,
  PrerecordingsEventListResponses,
  PrerecordingsEventStartDeleteErrors,
  PrerecordingsEventStartDeleteRequest,
  PrerecordingsEventStartDeleteResponses,
  PrerecordingsEventStartDownloadErrors,
  PrerecordingsEventStartDownloadRequest,
  PrerecordingsEventStartDownloadResponses,
  PrerecordingsEventStartHeaddownloadErrors,
  PrerecordingsEventStartHeaddownloadRequest,
  PrerecordingsEventStartHeaddownloadResponses,
  PrerecordingsEventStartUploadErrors,
  PrerecordingsEventStartUploadRequest,
  PrerecordingsEventStartUploadResponses,
  SseSubscribeErrors,
  SseSubscribeRequest,
  SseSubscribeResponses,
  TestTestErrors,
  TestTestRequest,
  TestTestResponses,
} from "./types";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class HeyApiClient {
  protected client: Client;

  constructor(args: { client: Client }) {
    this.client = args.client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = "default";

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(
        `No SDK client found. Create one with "new Sdk()" to fix this error.`,
      );
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry = new HeyApiRegistry<Sdk>();

  constructor(args: { client: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args.key);
  }

  /**
   * Ping
   *
   * Ping.
   */
  public pingPing<ThrowOnError extends boolean = false>(
    options?: Options<PingPingRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      PingPingResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PingPingRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PingPingResponseSchema.parseAsync(data),
      url: "/ping",
      ...options,
    });
  }

  /**
   * Ping headers
   *
   * Ping headers.
   */
  public pingHeadping<ThrowOnError extends boolean = false>(
    options?: Options<PingHeadpingRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).head<
      PingHeadpingResponses,
      unknown,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PingHeadpingRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PingHeadpingResponseSchema.parseAsync(data),
      url: "/ping",
      ...options,
    });
  }

  /**
   * Delete prerecording
   *
   * Delete a prerecording.
   */
  public prerecordingsEventStartDelete<ThrowOnError extends boolean = false>(
    options: Options<PrerecordingsEventStartDeleteRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).delete<
      PrerecordingsEventStartDeleteResponses,
      PrerecordingsEventStartDeleteErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PrerecordingsEventStartDeleteRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PrerecordingsEventStartDeleteResponseSchema.parseAsync(data),
      url: "/prerecordings/{event}/{start}",
      ...options,
    });
  }

  /**
   * Download prerecording
   *
   * Download a prerecording.
   */
  public prerecordingsEventStartDownload<ThrowOnError extends boolean = false>(
    options: Options<PrerecordingsEventStartDownloadRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      PrerecordingsEventStartDownloadResponses,
      PrerecordingsEventStartDownloadErrors,
      ThrowOnError
    >({
      parseAs: "stream",
      requestValidator: async (data) =>
        await PrerecordingsEventStartDownloadRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PrerecordingsEventStartDownloadResponseSchema.parseAsync(data),
      url: "/prerecordings/{event}/{start}",
      ...options,
    });
  }

  /**
   * Download prerecording headers
   *
   * Download prerecording headers.
   */
  public prerecordingsEventStartHeaddownload<
    ThrowOnError extends boolean = false,
  >(
    options: Options<PrerecordingsEventStartHeaddownloadRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).head<
      PrerecordingsEventStartHeaddownloadResponses,
      PrerecordingsEventStartHeaddownloadErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PrerecordingsEventStartHeaddownloadRequestSchema.parseAsync(data),
      url: "/prerecordings/{event}/{start}",
      ...options,
    });
  }

  /**
   * Upload prerecording
   *
   * Upload a prerecording.
   */
  public prerecordingsEventStartUpload<ThrowOnError extends boolean = false>(
    options: Options<PrerecordingsEventStartUploadRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).put<
      PrerecordingsEventStartUploadResponses,
      PrerecordingsEventStartUploadErrors,
      ThrowOnError
    >({
      bodySerializer: null,
      // @ts-expect-error
      duplex: "half",
      requestValidator: async (data) =>
        await PrerecordingsEventStartUploadRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PrerecordingsEventStartUploadResponseSchema.parseAsync(data),
      url: "/prerecordings/{event}/{start}",
      ...options,
    });
  }

  /**
   * List prerecordings
   *
   * List prerecordings.
   */
  public prerecordingsEventList<ThrowOnError extends boolean = false>(
    options: Options<PrerecordingsEventListRequest, ThrowOnError>,
  ) {
    return (options.client ?? this.client).get<
      PrerecordingsEventListResponses,
      PrerecordingsEventListErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await PrerecordingsEventListRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await PrerecordingsEventListResponseSchema.parseAsync(data),
      url: "/prerecordings/{event}",
      ...options,
    });
  }

  /**
   * Get SSE stream
   *
   * Get a stream of Server-Sent Events.
   */
  public sseSubscribe<ThrowOnError extends boolean = false>(
    options?: Options<SseSubscribeRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).sse.get<
      SseSubscribeResponses,
      SseSubscribeErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await SseSubscribeRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await SseSubscribeResponseSchema.parseAsync(data),
      url: "/sse",
      ...options,
    });
  }

  /**
   * Test
   *
   * Test.
   */
  public testTest<ThrowOnError extends boolean = false>(
    options?: Options<TestTestRequest, ThrowOnError>,
  ) {
    return (options?.client ?? this.client).get<
      TestTestResponses,
      TestTestErrors,
      ThrowOnError
    >({
      requestValidator: async (data) =>
        await TestTestRequestSchema.parseAsync(data),
      responseValidator: async (data) =>
        await TestTestResponseSchema.parseAsync(data),
      url: "/test",
      ...options,
    });
  }
}
