// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type UploadRequestType = string;

export type UploadRequestStart = string;

export type UploadRequestEvent = string;

/**
 * Result
 *
 * Result of the test.
 */
export type TestResponseResult = {
  /**
   * Success
   *
   * Indicates if the test was successful.
   */
  success: boolean;
  /**
   * Message
   *
   * Message returned from the test.
   */
  message: string;
};

export type TestRequestParameters = Parameters | null;

/**
 * Parameters
 *
 * Parameters for testing.
 */
export type Parameters = {
  /**
   * Message
   *
   * Optional message to include in the test.
   */
  message?: string | null;
};

export type SubscribeRequestTypes = string | Array<EventType> | null;

/**
 * EventType
 *
 * Event types.
 */
export type EventType = "test";

/**
 * Prerecording
 *
 * Prerecording data.
 */
export type Prerecording = {
  /**
   * Event
   *
   * Identifier of the event.
   */
  event: string;
  start: NaiveDatetime;
};

export type NaiveDatetime = string;

/**
 * PrerecordingList
 *
 * List of prerecordings.
 */
export type ListResponseResults = {
  /**
   * Count
   *
   * Total number of prerecordings that match the request.
   */
  count: number;
  /**
   * Limit
   *
   * Maximum number of returned prerecordings.
   */
  limit: number | null;
  /**
   * Offset
   *
   * Number of skipped prerecordings.
   */
  offset: number | null;
  /**
   * Prerecordings
   *
   * List of prerecordings.
   */
  prerecordings: Array<Prerecording>;
};

export type ListRequestOrder = ListOrder | null;

/**
 * ListOrder
 *
 * Order to list prerecordings.
 */
export type ListOrder = "asc" | "desc";

export type ListRequestOffset = number | null;

export type ListRequestLimit = number | null;

export type ListRequestEvent = string;

export type ListRequestBefore = NaiveDatetime | null;

export type ListRequestAfter = NaiveDatetime | null;

export type HeadDownloadRequestStart = string;

export type HeadDownloadRequestEvent = string;

export type DownloadRequestStart = string;

export type DownloadRequestEvent = string;

export type DeleteRequestStart = string;

export type DeleteRequestEvent = string;

export type PingPingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingPingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingPingResponse = PingPingResponses[keyof PingPingResponses];

export type PingHeadpingRequest = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type PingHeadpingResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PingHeadpingResponse =
  PingHeadpingResponses[keyof PingHeadpingResponses];

export type PrerecordingsEventStartDeleteRequest = {
  body?: never;
  path: {
    event: DeleteRequestEvent;
    start: DeleteRequestStart;
  };
  query?: never;
  url: "/prerecordings/{event}/{start}";
};

export type PrerecordingsEventStartDeleteErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PrerecordingsEventStartDeleteError =
  PrerecordingsEventStartDeleteErrors[keyof PrerecordingsEventStartDeleteErrors];

export type PrerecordingsEventStartDeleteResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PrerecordingsEventStartDeleteResponse =
  PrerecordingsEventStartDeleteResponses[keyof PrerecordingsEventStartDeleteResponses];

export type PrerecordingsEventStartDownloadRequest = {
  body?: never;
  path: {
    event: DownloadRequestEvent;
    start: DownloadRequestStart;
  };
  query?: never;
  url: "/prerecordings/{event}/{start}";
};

export type PrerecordingsEventStartDownloadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PrerecordingsEventStartDownloadError =
  PrerecordingsEventStartDownloadErrors[keyof PrerecordingsEventStartDownloadErrors];

export type PrerecordingsEventStartDownloadResponses = {
  /**
   * Stream Response
   */
  200: ReadableStream;
};

export type PrerecordingsEventStartDownloadResponse =
  PrerecordingsEventStartDownloadResponses[keyof PrerecordingsEventStartDownloadResponses];

export type PrerecordingsEventStartHeaddownloadRequest = {
  body?: never;
  path: {
    event: HeadDownloadRequestEvent;
    start: HeadDownloadRequestStart;
  };
  query?: never;
  url: "/prerecordings/{event}/{start}";
};

export type PrerecordingsEventStartHeaddownloadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PrerecordingsEventStartHeaddownloadError =
  PrerecordingsEventStartHeaddownloadErrors[keyof PrerecordingsEventStartHeaddownloadErrors];

export type PrerecordingsEventStartHeaddownloadResponses = {
  /**
   * Request fulfilled, headers follow
   */
  200: unknown;
};

export type PrerecordingsEventStartUploadRequest = {
  body: ReadableStream;
  headers: {
    /**
     * UploadRequestType
     *
     * Type of the prerecording data.
     */
    "Content-Type": UploadRequestType | string;
  };
  path: {
    event: UploadRequestEvent;
    start: UploadRequestStart;
  };
  query?: never;
  url: "/prerecordings/{event}/{start}";
};

export type PrerecordingsEventStartUploadErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PrerecordingsEventStartUploadError =
  PrerecordingsEventStartUploadErrors[keyof PrerecordingsEventStartUploadErrors];

export type PrerecordingsEventStartUploadResponses = {
  /**
   * Request fulfilled, nothing follows
   */
  204: void;
};

export type PrerecordingsEventStartUploadResponse =
  PrerecordingsEventStartUploadResponses[keyof PrerecordingsEventStartUploadResponses];

export type PrerecordingsEventListRequest = {
  body?: never;
  path: {
    event: ListRequestEvent;
  };
  query?: {
    /**
     * Only list prerecordings after this datetime (in event timezone).
     */
    after?: ListRequestAfter | string | null;
    /**
     * Only list prerecordings before this datetime (in event timezone).
     */
    before?: ListRequestBefore | string | null;
    /**
     * Maximum number of prerecordings to return. Default is 10.
     */
    limit?: ListRequestLimit | string | null;
    /**
     * Number of prerecordings to skip.
     */
    offset?: ListRequestOffset | string | null;
    /**
     * Order to apply to the results.
     */
    order?: ListRequestOrder | string | null;
  };
  url: "/prerecordings/{event}";
};

export type PrerecordingsEventListErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
  /**
   * Not Found Exception
   */
  404: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type PrerecordingsEventListError =
  PrerecordingsEventListErrors[keyof PrerecordingsEventListErrors];

export type PrerecordingsEventListResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: ListResponseResults;
};

export type PrerecordingsEventListResponse =
  PrerecordingsEventListResponses[keyof PrerecordingsEventListResponses];

export type SseSubscribeRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Types of events to subscribe to.
     */
    types?: SubscribeRequestTypes | string | null;
  };
  url: "/sse";
};

export type SseSubscribeErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type SseSubscribeError = SseSubscribeErrors[keyof SseSubscribeErrors];

export type SseSubscribeResponses = {
  /**
   * Request fulfilled, stream of Server-Sent Events follows
   */
  200: string;
};

export type SseSubscribeResponse =
  SseSubscribeResponses[keyof SseSubscribeResponses];

export type TestTestRequest = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Parameters for testing.
     */
    parameters?: TestRequestParameters | string | null;
  };
  url: "/test";
};

export type TestTestErrors = {
  /**
   * Validation Exception
   */
  400: {
    status_code: number;
    detail: string;
    extra?:
      | null
      | {
          [key: string]: unknown;
        }
      | Array<unknown>;
  };
};

export type TestTestError = TestTestErrors[keyof TestTestErrors];

export type TestTestResponses = {
  /**
   * Request fulfilled, document follows
   */
  200: TestResponseResult;
};

export type TestTestResponse = TestTestResponses[keyof TestTestResponses];
