/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ping
     * @description Ping.
     */
    get: operations["PingPing"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    /**
     * Ping headers
     * @description Ping headers.
     */
    head: operations["PingHeadping"];
    patch?: never;
    trace?: never;
  };
  "/prerecordings/{event}/{start}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download prerecording
     * @description Download a prerecording.
     */
    get: operations["PrerecordingsEventStartDownload"];
    /**
     * Upload prerecording
     * @description Upload a prerecording.
     */
    put: operations["PrerecordingsEventStartUpload"];
    post?: never;
    /**
     * Delete prerecording
     * @description Delete a prerecording.
     */
    delete: operations["PrerecordingsEventStartDelete"];
    options?: never;
    /**
     * Download prerecording headers
     * @description Download prerecording headers.
     */
    head: operations["PrerecordingsEventStartHeaddownload"];
    patch?: never;
    trace?: never;
  };
  "/prerecordings/{event}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List prerecordings
     * @description List prerecordings.
     */
    get: operations["PrerecordingsEventList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Prerecording */
    Prerecording: {
      /**
       * Format: uuid
       * @description Identifier of the event.
       */
      event: string;
      /**
       * Format: date-time
       * @description Start time of the event instance in event timezone.
       */
      start: string;
    };
    /** PrerecordingList */
    PrerecordingList: {
      /** @description Total number of prerecordings that match the request. */
      count: number;
      /** @description Maximum number of returned prerecordings. */
      limit?: null | number;
      /** @description Number of skipped prerecordings. */
      offset?: null | number;
      /** @description List of prerecordings. */
      prerecordings: components["schemas"]["Prerecording"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  PingPing: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          "cache-control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": null;
        };
      };
    };
  };
  PingHeadping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          "cache-control"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": null;
        };
      };
    };
  };
  PrerecordingsEventStartDownload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Identifier of the event. */
        event: string;
        /** @description Start time of the event instance in event timezone. */
        start: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Stream Response */
      200: {
        headers: {
          /** @description File size in bytes */
          "content-length"?: string;
          /** @description Last modified data-time in RFC 2822 format */
          "last-modified"?: string;
          /** @description Entity tag */
          etag?: string;
          /** @description Last modified. */
          "Last-Modified"?: unknown;
          /** @description Content length. */
          "Content-Length"?: unknown;
          /** @description Entity tag. */
          ETag?: unknown;
          /** @description Content type. */
          "Content-Type"?: unknown;
          [name: string]: unknown;
        };
        content: {
          "": string;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  PrerecordingsEventStartUpload: {
    parameters: {
      query?: never;
      header: {
        /** @description Type of the prerecording data. */
        "Content-Type": string;
      };
      path: {
        /** @description Identifier of the event. */
        event: string;
        /** @description Start time of the event instance in event timezone. */
        start: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": null;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  PrerecordingsEventStartDelete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Identifier of the event. */
        event: string;
        /** @description Start time of the event instance in event timezone. */
        start: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, nothing follows */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": null;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  PrerecordingsEventStartHeaddownload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Identifier of the event. */
        event: string;
        /** @description Start time of the event instance in event timezone. */
        start: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
          /** @description Last modified. */
          "Last-Modified"?: unknown;
          /** @description Content length. */
          "Content-Length"?: unknown;
          /** @description Entity tag. */
          ETag?: unknown;
          /** @description Content type. */
          "Content-Type"?: unknown;
          [name: string]: unknown;
        };
        content: {
          "application/json": null;
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
  PrerecordingsEventList: {
    parameters: {
      query?: {
        /** @description Only list prerecordings after this time (in event timezone). */
        after?: null | string;
        /** @description Only list prerecordings before this time (in event timezone). */
        before?: null | string;
        /** @description Maximum number of prerecordings to return. */
        limit?: null | number;
        /** @description Number of prerecordings to skip. */
        offset?: null | number;
        /** @description Order to apply to the results. */
        order?: "asc" | "desc" | null;
      };
      header?: never;
      path: {
        /** @description Identifier of the event to list prerecordings for. */
        event: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request fulfilled, document follows */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrerecordingList"];
        };
      };
      /** @description Bad request syntax or unsupported method */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            status_code: number;
            detail: string;
            extra?:
              | null
              | {
                  [key: string]: unknown;
                }
              | unknown[];
          };
        };
      };
    };
  };
}
